version: '3'
services:
  golang:
    image: hopher/golang:latest
    container_name: my_golang
    build: ./go/
    ports:
      - "1313:1313"
    volumes:
      - ~/src:/go/src:rw    
    stdin_open: true
    tty: true

  php:
    image: hopher/php:7.2-fpm
    container_name: my_php
    build: ./php/
    ports:
      - "9000:9000"
    volumes:
      - ~/src:/var/www/html:rw
    restart: always
    command: php-fpm
  
  nginx:
    image: hopher/nginx:latest
    container_name: my_nginx    
    build: ./nginx
    depends_on:
      - php
    links:  # links 为 services name
      - php:php-fpm
    ports:
      - "80:80"
      - "443:443"
    restart: always
    command: nginx -g 'daemon off;'

  mysql:
    image: hopher/mysql:5.7
    container_name: my_mysql    
    build: ./mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456      
    restart: always
    command: "--character-set-server=utf8"

  redis:
      build: ./redis
      ports:
        - "6379:6379"
      restart: always      
      